# To release:
# git tag v0.1.0
# git push origin v0.1.0
# GITHUB_TOKEN=... goreleaser
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"

snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
kos:
  - repository: ghcr.io/howardjohn/kubeconfig-proxy
    bare: true
    labels:
      org.opencontainers.image.source: https://github.com/howardjohn/kubeconfig-proxy
    tags:
      - "{{.Version}}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64